correct: isPrime-correct.c isPrime-broken1.c isPrime-broken2.c isPrime-broken3.c isPrime-broken4.c
	gcc -o correct -pedantic -std=gnu99 -Wall -Werror isPrime-correct.c
broken1: isPrime-broken1.c
	gcc -o broken1 -pedantic -std=gnu99 -Wall -Werror isPrime-broken1.c
broken2: isPrime-broken2.c
	gcc -o broken2 -pedantic -std=gnu99 -Wall -Werror isPrime-broken2.c
broken3: isPrime-broken2.c
	gcc -o broken3 -pedantic -std=gnu99 -Wall -Werror isPrime-broken3.c
broken4: isPrime-broken4.c
	gcc -o broken4 -pedantic -std=gnu99 -Wall -Werror isPrime-broken4.c
